#!/usr/bin/env bash
# ca-init.sh — create the rig's root CA and its runtime secrets on first `up`.
#
#   .v2/ca/root_ca.crt + root_ca_key   root of trust for step-ca (app VM), every VM's
#                                      trust store, the gateway edges and the kits.
#   .v2/shared-secrets/rig-secrets.env  step-ca admin/provisioner passwords, generated
#                                      once, sourced by `vmlab.sh stack` (rig-only).
#
# Both are host-side, gitignored, and idempotent: existing files are kept.
# Regenerating the CA after VMs exist requires `down.sh` first (step-ca's data
# volume and the shared provisioner secrets are bound to the old root).
set -euo pipefail
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CA_DIR="$HERE/.v2/ca"; SEC_DIR="$HERE/.v2/shared-secrets"
mkdir -p "$CA_DIR" "$SEC_DIR"

if [[ ! -f "$CA_DIR/root_ca.crt" || ! -f "$CA_DIR/root_ca_key" ]]; then
    echo "[ca] generating rig root CA in $CA_DIR"
    if command -v step >/dev/null 2>&1; then
        step certificate create "CoreWAF Demo Rig Root CA" "$CA_DIR/root_ca.crt" "$CA_DIR/root_ca_key" \
            --profile root-ca --no-password --insecure --not-after 87600h >/dev/null
    elif command -v docker >/dev/null 2>&1; then
        docker run --rm -u "$(id -u):$(id -g)" -v "$CA_DIR:/ca" smallstep/step-cli:0.27.5 \
            step certificate create "CoreWAF Demo Rig Root CA" /ca/root_ca.crt /ca/root_ca_key \
            --profile root-ca --no-password --insecure --not-after 87600h >/dev/null
    else
        openssl req -x509 -newkey ec -pkeyopt ec_paramgen_curve:prime256v1 -nodes -days 3650 \
            -subj "/CN=CoreWAF Demo Rig Root CA" -keyout "$CA_DIR/root_ca_key" -out "$CA_DIR/root_ca.crt" \
            -addext "basicConstraints=critical,CA:TRUE" -addext "keyUsage=critical,keyCertSign,cRLSign" 2>/dev/null
    fi
    chmod 600 "$CA_DIR/root_ca_key"
else
    echo "[ca] root CA present ($CA_DIR)"
fi

if [[ ! -f "$SEC_DIR/rig-secrets.env" ]]; then
    echo "[ca] generating rig secrets ($SEC_DIR/rig-secrets.env)"
    rnd() { head -c 24 /dev/urandom | base64 | tr -d '/+=' ; }
    umask 077
    cat >"$SEC_DIR/rig-secrets.env" <<EOF2
# generated by ca-init.sh — rig-only, never commit
STEPCA_PASSWORD=$(rnd)
STEPCA_PROVISIONER_PASSWORD=$(rnd)
EOF2
else
    echo "[ca] rig secrets present"
fi
