#!/bin/sh
# install-v2.sh — bring up the real corewaf-starter-kit inside a v2-rig kit VM.
#
# v2 deltas vs the single-host vm/kit-shim/install-rig-kit.sh:
#   - The kit VM's resolv.conf points at the dns VMs, so the tunnel container
#     resolves gw-1.rig.internal itself (docker embedded DNS forwards to the
#     VM resolver). No extra_hosts mapping for the gw URL.
#   - The redeem-returned WG endpoint (from the TunnelServer record) is already
#     correct AND resolvable — no NL_SERVER_ENDPOINT_OVERRIDE.
#   - The kit self-locates ENTIRELY from the token's `gw` claim: it posts both
#     /redeem and /reconnect there (the network-loader defaults the reconnect
#     base to the token gw, and the v2 edge folded the former mTLS :444 onto
#     :443). No reconnect-URL override — the token is the single source of
#     truth for which gateway this kit homes to.
#
# Inputs (env, set by kit-up.sh):
#   KIT_TOKEN          provisioning token (carries the gw + namespace claim)
#   KIT_REPO_DIR       staged kit tree (default /opt/corewaf-starter-kit)
#   CA_BUNDLE          rig root CA inside the VM (-> runtime/operator-ca.crt)
set -eu

KIT_REPO_DIR="${KIT_REPO_DIR:-/opt/corewaf-starter-kit}"
STATE_DIR="${STATE_DIR:-/run/kit-state}"
CA_BUNDLE="${CA_BUNDLE:-}"

[ -n "${KIT_TOKEN:-}" ] || { echo "install-v2: KIT_TOKEN required" >&2; exit 2; }
[ -d "$KIT_REPO_DIR" ] || { echo "install-v2: KIT_REPO_DIR=$KIT_REPO_DIR missing" >&2; exit 2; }

mkdir -p "$STATE_DIR"; chmod 700 "$STATE_DIR"
mkdir -p "$KIT_REPO_DIR/runtime"
[ -f "$CA_BUNDLE" ] && cp "$CA_BUNDLE" "$KIT_REPO_DIR/runtime/operator-ca.crt"

cd "$KIT_REPO_DIR"
TOKEN="$KIT_TOKEN" INSTANCE_COMMENT="rig2-vm-kit" bash scripts/install.sh --no-up

cat > "$KIT_REPO_DIR/docker-compose.override.yml" <<EOF
# v2-rig override — autogenerated by v2/kit-shim/install-v2.sh.
# The kit self-locates from the token's gw claim — redeem AND reconnect both
# go there (network-loader defaults the reconnect base to the token gw), so
# there is NO reconnect-URL override. resolv.conf -> dns VMs resolves the gw
# FQDN. Only the PKCS#11/TPM wiring + the tunnel command remain.
services:
  tunnel:
    environment:
      NL_PKCS11_PIN: "0000"
      TPM2_PKCS11_STORE: "/var/lib/tunnel/pkcs11-store"
    command: ["tunnel"]
EOF

echo "EVENT phase=config hwId=pending"
docker compose up -d
echo "EVENT phase=compose-up status=started"

deadline=$(($(date +%s) + 180))
status=""
while [ "$(date +%s)" -lt "$deadline" ]; do
    status="$(docker compose ps --format '{{.Health}}' tunnel 2>/dev/null | head -1)"
    [ "$status" = "healthy" ] && break
    sleep 3
done
[ "$status" = "healthy" ] || {
    echo "install-v2: tunnel did not become healthy" >&2
    docker compose logs --tail=100 tunnel >&2
    exit 1
}
echo "EVENT phase=tunnel-healthy"

TUNNEL_STATE_VOL="$(docker volume inspect tunnel_state --format '{{.Mountpoint}}' 2>/dev/null)" || true
if [ -n "$TUNNEL_STATE_VOL" ] && [ -d "$TUNNEL_STATE_VOL" ]; then
    pluck() { python3 -c "import json,sys; d=json.load(open('$TUNNEL_STATE_VOL/$1')); print(d.get('$2',''))" 2>/dev/null || true; }
    pluck discovery.json   instance_name   > "$STATE_DIR/hwId"            || true
    pluck operational.json clientIP        > "$STATE_DIR/client.ip"       || true
    pluck operational.json server_endpoint > "$STATE_DIR/server.endpoint" || true
    pluck operational.json server_pubkey   > "$STATE_DIR/server.pubkey"   || true
fi
echo "EVENT phase=persist hwId=$(cat "$STATE_DIR/hwId" 2>/dev/null) clientIP=$(cat "$STATE_DIR/client.ip" 2>/dev/null)"
echo "EVENT install-v2=ok"
